---
- name: Upload configuration for Keepalived
  block:
  - name: Create folder
    ansible.builtin.file:
      dest: /etc/keepalived
      state: directory
  - name: Upload configuration
    ansible.builtin.template:
      src: keepalived.conf.j2
      dest: /etc/keepalived/keepalived.conf
  - name: Upload health check
    ansible.builtin.template:
      src: check_apiserver.sh.j2
      dest: /etc/keepalived/check_apiserver.sh
      mode: 0755
  - name: Upload Kubernetes manifest
    ansible.builtin.copy:
      src: keepalived.yaml
      dest: /etc/kubernetes/manifests/keepalived.yaml

- name: Upload configuration for HAproxy
  block:
  - name: Create folder
    ansible.builtin.file:
      dest: /etc/haproxy
      state: directory
  - name: Upload configuration
    ansible.builtin.template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
  - name: Upload Kubernetes manifest
    ansible.builtin.copy:
      src: haproxy.yaml
      dest: /etc/kubernetes/manifests/haproxy.yaml

- name: Bootstrap cluster
  include_tasks: bootstrap-cluster.yml
...